export const sellerPaths = {
  root: '/seller',
  dashboard: '/seller',
  agencies: '/seller/agencies',
  agencyNew: '/seller/agencies/new',
  agency: (id: string) => `/seller/agencies/${encodeURIComponent(id)}`,
  store: '/seller/store',
  orders: '/seller/orders',
  orderNew: '/seller/orders/new',
  order: (orderCode: string) => `/seller/orders/${encodeURIComponent(orderCode)}`,
  payments: '/seller/payments',
  tracking: '/seller/tracking',
  quotations: '/seller/quotations',
  quotationNew: '/seller/quotations/new',
  quotation: (id: string) => `/seller/quotations/${encodeURIComponent(id)}`,
} as const
